import type { FaqItemType } from '../types/Faq';

export const FAQ_LIST: FaqItemType[] = [
  {
    id: 11,
    question: '회원 탈퇴는 어떻게 하나요?',
    answer: '마이페이지 > 회원 정보 > 탈퇴하기에서 진행할 수 있습니다.',
    category: '기타',
    updatedAt: '2026-07-06',
  },
  {
    id: 10,
    question: '영양제 추천은 어떤 식인가요?',
    answer: '식약처 데이터를 기반으로 서비스 내 자체 기준에 따라 추천합니다.',
    category: '추천/성분',
    updatedAt: '2026-07-06',
  },
  {
    id: 9,
    question: '프리미엄 서비스 환불 가능한가요?',
    answer: '현재 프리미엄 서비스 환불 정책을 확인해 주세요.',
    category: '기타',
    updatedAt: '2026-07-06',
  },
  {
    id: 8,
    question: '연속 섭취일 복구 방법 없나요?',
    answer: '현재는 존재하지 않습니다.',
    category: '복용/섭취',
    updatedAt: '2026-07-06',
  },
  {
    id: 7,
    question: '섭취 알림은 어떻게 설정하나요?',
    answer: '영양제 보관함에서 섭취 시간과 알림을 설정할 수 있습니다.',
    category: '알림',
    updatedAt: '2026-07-05',
  },
  {
    id: 6,
    question: '추천 결과는 다시 받을 수 있나요?',
    answer: '건강 설문을 다시 작성하면 새로운 추천 결과를 받을 수 있습니다.',
    category: '추천/성분',
    updatedAt: '2026-07-05',
  },
  {
    id: 5,
    question: '영양제 섭취 기록을 수정할 수 있나요?',
    answer: '섭취 기록 화면에서 날짜별 기록을 수정할 수 있습니다.',
    category: '복용/섭취',
    updatedAt: '2026-07-04',
  },
  {
    id: 4,
    question: '알림이 오지 않아요.',
    answer: '기기의 알림 권한과 서비스 내 알림 설정을 확인해 주세요.',
    category: '알림',
    updatedAt: '2026-07-04',
  },
  {
    id: 3,
    question: '추천 성분의 기준이 궁금해요.',
    answer: '건강 설문과 공공 데이터를 종합해 필요한 성분을 안내합니다.',
    category: '추천/성분',
    updatedAt: '2026-07-03',
  },
  {
    id: 2,
    question: '복용 시간을 변경하고 싶어요.',
    answer: '영양제 상세 설정에서 복용 시간을 변경할 수 있습니다.',
    category: '복용/섭취',
    updatedAt: '2026-07-02',
  },
  {
    id: 1,
    question: '문의는 어디에서 남길 수 있나요?',
    answer: '마이페이지의 문의하기 메뉴를 이용해 주세요.',
    category: '기타',
    updatedAt: '2026-07-01',
  },
];
